# Generated by Django 5.0.4 on 2024-05-17 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_user_first_name_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250)),
                ('time', models.IntegerField(max_length=250)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_conference', to='classroom.teacher')),
            ],
        ),
    ]
