# Generated by Django 5.0.4 on 2024-05-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_videoconference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoconference',
            name='time',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
    ]
